name: Callable deploy workflow

on:
  workflow_call:
    inputs:
      aws_environment:
        type: string
        required: true
      aws_region:
        type: string
        default: 'eu-central-1'
    secrets:
      SLACK_DEPLOY_WEBHOOK_URL:
        required: true

jobs:
  deploy:
    name: Deploy ${{ inputs.aws_environment }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Deploy frontend to ${{ inputs.aws_environment }}
        run: echo "foo"

  slackNotification:
    if: ${{ always() }}
    needs: deploy
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: kompetansekartlegging-deployments
          SLACK_COLOR: ${{ needs.deploy.result }}
          SLACK_USERNAME: Kompetansekartlegging deploy bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_DEPLOY_WEBHOOK_URL }}
          SLACK_MESSAGE: '${{ github.event.head_commit.message }} :rocket:'