name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS environment
        type: choice
        options:
          - dev
          - prod

jobs: 
  check_for_changes:
    name: Check for changes
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check if changes to frontend
        id: frontend
        uses: tj-actions/changed-files@v35
        with:
          files: frontend* # Includes frontend/* and frontend-cdk/*
      
      - name: Log changes
        run: |
           echo "Frontend has changes: ${{ steps.frontend.outputs.any_changed == 'true' }}"
           echo "List all the files that have changed: ${{ steps.frontend.outputs.all_changed_files }}"

      - name: Check if changes to backend
        id: backend
        uses: tj-actions/changed-files@v35
        with:
          files: cdk/* 
          
      - name: Log Changes
        run: |
           echo "Backend has changes: ${{ steps.backend.outputs.any_changed == 'true' }}"
           echo "List all the files that have changed: ${{ steps.backend.outputs.all_changed_files }}"
      
    outputs:
      frontend: ${{ steps.frontend.outputs.any_changed }}
      backend: ${{ steps.backend.outputs.any_changed }}
      has_changes: ${{ steps.frontend.outputs.any_changed == 'true' || steps.backend.outputs.any_changed == 'true' }}

  deploy_dev_on_push_main:
    needs: check_for_changes
    if: (github.event_name == 'push' && ${{ needs.check_for_changes.outputs.has_changes == 'true' }})
    name: Deploy dev on push to main
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: dev
      deploy_frontend: ${{ fromJSON(needs.check_for_changes.outputs.frontend) }}
      deploy_backend: ${{ fromJSON(needs.check_for_changes.outputs.backend) }}
    secrets:
      aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY}}    
      

  deploy_on_workflow_dispatch:
    needs: check_for_changes
    if: (github.event_name == 'workflow_dispatch' && ${{ fromJson(needs.check_for_changes.outputs.has_changes) }})
    name: Deploy on dispatch
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: ${{ inputs.aws_environment }}
      deploy_frontend: ${{ fromJSON(needs.check_for_changes.outputs.frontend) }}
      deploy_backend: ${{ fromJSON(needs.check_for_changes.outputs.backend) }}
    secrets:
      aws_access_key_id: ${{ inputs.aws_environment == 'prod' && secrets.PROD_AWS_ACCESS_KEY_ID || secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ inputs.aws_environment == 'prod' && secrets.PROD_AWS_SECRET_ACCESS_KEY || secrets.DEV_AWS_SECRET_ACCESS_KEY}}
