name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS environment
        type: choice
        options:
          - dev
          - prod

jobs: 
  deploy_dev_on_push_main:
    if: github.event_name == 'push'
    name: Deploy dev on push to main
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: dev

  deploy_on_workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    name: Deploy on dispatch
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: ${{ inputs.aws_environment }}
