name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS environment
        type: choice
        options:
          - dev
          - prod

jobs: 
  check_for_changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - name: Check if frontend has changed
      id: frontend
      uses: tj-actions/changed-files@v35
      with:
        - frontend* # Includes frontend/* and frontend-cdk/*
      run: |
        echo  "deploy_frontend="${{ steps.frontend.outputs.any_changed }} >> $GITHUB_ENV

      - name: Check if backend has changed
      id: backend
      uses: tj-actions/changed-files@v35
      with:
        - cdk* 
      run: |
        echo  $ {{ steps.backend.outputs.any_changed }} >> $GITHUB_ENV

  deploy_dev_on_push_main:
    needs: check_for_changes
    if: github.event_name == 'push' && ${{ env.backend_changed || env.frontend_changed }}
    name: Deploy dev on push to main
      uses: ./.github/workflows/callable-deploy.yml
      with:
        aws_environment: dev
        deploy_frontend: ${{ env.frontend_changed }}
        deploy_backend: ${{ env.backend_changed }}
      secrets:
        aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY}}    
      

  deploy_on_workflow_dispatch:
    needs: check_for_changes
    if: github.event_name == 'workflow_dispatch' && ${{ env.backend_changed || env.frontend_changed }}
    name: Deploy on dispatch
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: ${{ inputs.aws_environment }}
      deploy_frontend: ${{ env.backend_changed }}
      deploy_backend: ${{ env.backend_changed }}
    secrets:
      aws_access_key_id: ${{ inputs.aws_environment == 'prod' && secrets.PROD_AWS_ACCESS_KEY_ID || secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ inputs.aws_environment == 'prod' && secrets.PROD_AWS_SECRET_ACCESS_KEY || secrets.DEV_AWS_SECRET_ACCESS_KEY}}