name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS environment
        type: choice
        options:
          - dev
          - prod

jobs: 
  check_files:
      name: Check if needs deployment
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 2

          - name: Check changed files
            id: check
            uses: tj-actions/changed-files@v35
            with:
              files_ignore: |
                */README.md
                *.sh
                scripts/*
                .github/dependabot.yml
                .github/workflows/frontend-eslint-prettier.yml
                .gitignore
                .github/ISSUE_TEMPLATE/*
              since_last_remote_commit: true
          - name: Log changes
            run: |
              echo "Any files changed: ${{ steps.check.outputs.any_modified }}"
              echo "Files: ${{ steps.check.outputs.all_modified_files }}"
      outputs:
        any_modified: ${{ steps.check.outputs.any_modified }}

  deploy_dev_on_push_main:
    needs: check_files
    if: github.event_name == 'push' && needs.check_files.outputs.any_modified == 'true'
    runs-on: ubuntu-latest
    steps:
      - id: push_main
        run: |
              echo "push_main"
      
  deploy_on_workflow_dispatch:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - id: workflow_dispatch
        run: |
              echo "workflow_dispatc"

      

    
