name: Deploy to AWS

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      aws_environment:
        description: AWS environment
        type: choice
        options:
          - dev
          - prod

jobs: 
  check_for_changes:
    name: Check if needs deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check if changes to frontend
        id: frontend
        uses: tj-actions/changed-files@v35
        with:
          files: frontend/* 
      
      - name: Check if changes to frontend-cdk
        id: frontend-cdk
        uses: tj-actions/changed-files@v35
        with:
          files: frontend-cdk/* 
      
      - name: Log changes
        run: |
           echo "Frontend has changes: ${{ fromJson(steps.frontend.outputs.any_modified) || fromJson(steps.frontend-cdk.outputs.any_modified) }}"
           echo "frontend/: ${{ steps.frontend.outputs.all_modified_files }}"
           echo "frontend-cdk/: ${{ steps.frontend-cdk.outputs.all_modified_files }}"


      - name: Check if changes to backend
        id: backend
        uses: tj-actions/changed-files@v35
        with:
          files: cdk/* 

      - name: Log changes
        run: |
           echo "Backend has changes: ${{ steps.backend.outputs.any_modified }}"
           echo "cdk/: ${{ steps.backend.outputs.all_modified_files }}"
    
    # These outputs are strings  
    outputs:
      frontend: ${{ fromJson(steps.frontend.outputs.any_modified) || fromJson(steps.frontend-cdk.outputs.any_modified) }}
      backend: ${{ fromJson(steps.backend.outputs.any_modified) }}

  fake_job:
    needs: check_for_changes
    if:  ${{ github.event_name == 'push' && fromJson(needs.check_for_changes.outputs.frontend) || fromJson(needs.check_for_changes.outputs.backend) }} #| github.event_name == 'push' && ${{ fromJson(needs.check_for_changes.outputs.frontend) || fromJson(needs.check_for_changes.outputs.backend) }}
    name: Fake Job
    runs-on: ubuntu-latest

    steps:
    - name: Foo
      run: |
        echo "Changes: ${{ fromJson(needs.check_for_changes.outputs.frontend) || fromJson(needs.check_for_changes.outputs.backend) }}"
        echo "Conditional: ${{ github.event_name == 'push' && fromJson(needs.check_for_changes.outputs.frontend) || fromJson(needs.check_for_changes.outputs.backend) }}"

  deploy_dev_on_push_main:
    needs: check_for_changes
    if: false #| github.event_name == 'push' && ${{ fromJson(needs.check_for_changes.outputs.frontend) || fromJson(needs.check_for_changes.outputs.backend) }}
    name: Deploy dev on push to main
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: dev
      deploy_frontend: ${{ fromJSON(needs.check_for_changes.outputs.frontend) }}
      deploy_backend: ${{ fromJSON(needs.check_for_changes.outputs.backend) }}
    secrets:
      aws_access_key_id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY}}    
      

  deploy_on_workflow_dispatch:
    needs: check_for_changes
    if: false # ${{ github.event_name == 'workflow_dispatch' && needs.check_for_changes.outputs.has_changes == 'true' }}
    name: Deploy on dispatch
    uses: ./.github/workflows/callable-deploy.yml
    with:
      aws_environment: ${{ inputs.aws_environment }}
      deploy_frontend: ${{ fromJSON(needs.check_for_changes.outputs.frontend) }}
      deploy_backend: ${{ fromJSON(needs.check_for_changes.outputs.backend) }}
    secrets:
      aws_access_key_id: ${{ inputs.aws_environment == 'prod' && secrets.PROD_AWS_ACCESS_KEY_ID || secrets.DEV_AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ inputs.aws_environment == 'prod' && secrets.PROD_AWS_SECRET_ACCESS_KEY || secrets.DEV_AWS_SECRET_ACCESS_KEY}}
